"""Interview engine - state machine for interview flow."""
from typing import Optional, Dict, List
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime
from backend.db.models import (
    InterviewSession, InterviewTurn, AskedQuestion, Evaluation,
    QuestionBank, Resume
)
from backend.core.config import settings
from backend.services.question_selector import select_question, adjust_difficulty
from backend.services.evaluator_rules import evaluate_answer
from backend.services.llm_provider import evaluate_with_llm, generate_followup_with_llm
from backend.services.adaptive_interview import AdaptiveInterviewEngine
from backend.services.audio_processor import process_audio_answer
from backend.services.expression_analyzer import analyze_expression
from backend.services.interview_phrases import (
    get_first_question_phrase,
    get_next_question_phrase,
    get_followup_phrase,
)


def create_session(
    db: Session,
    user_id: int,
    track: str,
    level: int,
    resume_id: Optional[int] = None,
    total_rounds: int = 10
) -> InterviewSession:
    """Create a new interview session."""
    session = InterviewSession(
        user_id=user_id,
        resume_id=resume_id,
        track=track,
        level=level,
        total_rounds=total_rounds,
        current_round=0,
        status="active"
    )
    db.add(session)
    db.commit()
    db.refresh(session)
    return session


def start_interview(db: Session, session_id: int) -> Optional[Dict]:
    """Start interview - get first question.

    When a resume is available and LLM is configured, the first question
    is generated by the LLM based on the candidate's resume, making the
    interview feel personalized from the very first turn.
    """
    session = db.query(InterviewSession).filter(InterviewSession.id == session_id).first()
    if not session or session.status != "active":
        return None

    # Get resume data if available
    resume_skills = None
    resume_parsed = None
    if session.resume_id:
        resume = db.query(Resume).filter(Resume.id == session.resume_id).first()
        if resume and resume.parsed_json:
            resume_parsed = resume.parsed_json
            resume_skills = resume_parsed.get("skills", [])

    # Strategy 1: LLM-generated first question from resume (most personalized)
    llm_q = None
    if resume_parsed and settings.zhipuai_api_key:
        try:
            from backend.services.llm_provider import generate_resume_question_llm
            llm_q = generate_resume_question_llm(
                resume_parsed=resume_parsed,
                track=session.track,
                difficulty=session.level,
            )
        except Exception:
            pass

    if llm_q:
        # LLM-generated question (not from bank)
        chapter = _infer_chapter_from_question(llm_q["question"], session.track)
        asked_q = AskedQuestion(
            session_id=session_id,
            qbank_id=None,
            topic=chapter,
            difficulty=session.level,
            question_text=llm_q["question"],
            correct_answer_text=llm_q["reference_answer"],
        )
        db.add(asked_q)

        intro_content = (
            f"你好！我看了你的简历，结合你的技术背景，我们从一个相关问题开始：\n\n"
            f"{llm_q['question']}"
        )
        interviewer_turn = InterviewTurn(
            session_id=session_id, role="interviewer", content=intro_content
        )
        db.add(interviewer_turn)
        session.current_round = 1
        db.commit()
        return {
            "question": llm_q["question"],
            "turn_id": interviewer_turn.id,
            "round": session.current_round,
        }

    # Strategy 2: Select from question bank (with resume-based chapter preference)
    question = select_question(
        db=db,
        session=session,
        current_difficulty=session.level,
        resume_skills=resume_skills,
    )

    if not question:
        return {"error": "题库中没有可用题目，请先导入题库。"}

    asked_q = AskedQuestion(
        session_id=session_id,
        qbank_id=question.id,
        topic=question.chapter,
        difficulty=question.difficulty,
        question_text=question.question,
        correct_answer_text=question.correct_answer,
    )
    db.add(asked_q)

    has_resume = bool(session.resume_id)
    intro_content = get_first_question_phrase(question.question, has_resume=has_resume)
    interviewer_turn = InterviewTurn(
        session_id=session_id, role="interviewer", content=intro_content
    )
    db.add(interviewer_turn)
    session.current_round = 1
    db.commit()

    return {
        "question": question.question,
        "turn_id": interviewer_turn.id,
        "round": session.current_round,
    }


def _infer_chapter_from_question(question_text: str, track: str) -> str:
    """Best-effort chapter inference for LLM-generated questions."""
    from difflib import SequenceMatcher
    track_chapters = settings.track_chapters.get(track, {})
    best_ch = list(track_chapters.keys())[0] if track_chapters else "Java基础"
    best_score = 0
    for ch in track_chapters:
        score = SequenceMatcher(None, question_text.lower(), ch.lower()).ratio()
        if score > best_score:
            best_score = score
            best_ch = ch
    return best_ch


def submit_answer(
    db: Session,
    session_id: int,
    answer_text: Optional[str] = None,
    answer_type: str = "text",
    audio_data: Optional[Dict] = None,
    expression_data: Optional[Dict] = None
) -> Dict:
    """Submit answer and get evaluation + next question.
    
    Args:
        db: Database session
        session_id: Interview session ID
        answer_text: Text answer (for text mode, required)
        answer_type: "text" or "audio"
        audio_data: Audio data dict with base64 audio and metadata (for audio mode)
        expression_data: Optional. Supports:
            - {"imageData": base64_str}: legacy single-photo mode
            - {"analyses": [...]}: real-time video mode, pre-computed analyses from video stream
    """
    # --- Agentic controller gate (feature flag) ---
    if getattr(settings, "enable_agent_controller", False):
        return _submit_answer_agentic(
            db, session_id, answer_text, answer_type, audio_data, expression_data
        )
    # --- End agentic gate; legacy path below ---

    session = db.query(InterviewSession).filter(InterviewSession.id == session_id).first()
    if not session or session.status != "active":
        return {"error": "面试会话不存在或已结束"}
    
    # Process answer based on type
    audio_analysis = None
    expression_analysis = None

    # Optional: facial expression - real-time analyses or legacy single image
    if expression_data:
        if expression_data.get("analyses"):
            # Real-time video mode: use most recent for this evaluation, append all to session history
            analyses = expression_data["analyses"]
            if analyses:
                # Remove internal _timestamp for storage
                latest = {k: v for k, v in analyses[-1].items() if not k.startswith("_")}
                expression_analysis = latest
            # Append to session-level expression history
            existing_history = session.expression_history_json or []
            for a in analyses:
                clean = {k: v for k, v in a.items() if not k.startswith("_")}
                existing_history.append(clean)
            session.expression_history_json = existing_history[-100:]  # Cap at 100 samples
        elif expression_data.get("imageData"):
            expression_analysis = analyze_expression(expression_data["imageData"], enforce_detection=False)
    
    if answer_type == "audio":
        if not audio_data:
            return {"error": "音频数据为空"}
        
        # Process audio: speech-to-text + audio analysis
        processed_result = process_audio_answer(audio_data)
        answer_text = processed_result["text"]
        audio_analysis = processed_result["audio_analysis"]
        
        # In chat show friendly text; full transcript used only for evaluation (stored in Evaluation)
        display_content = _normalize_candidate_display_content(
            answer_text if answer_text else ""
        )
        candidate_turn = InterviewTurn(
            session_id=session_id,
            role="candidate",
            content=display_content
        )
        db.add(candidate_turn)
        db.flush()
    else:
        # Text answer
        if not answer_text or not answer_text.strip():
            return {"error": "回答内容为空"}
        
        # Save candidate answer
        candidate_turn = InterviewTurn(
            session_id=session_id,
            role="candidate",
            content=answer_text
        )
        db.add(candidate_turn)
        db.flush()
    
    # Get current asked question
    asked_q = db.query(AskedQuestion).filter(
        AskedQuestion.session_id == session_id
    ).order_by(AskedQuestion.created_at.desc()).first()
    
    if not asked_q:
        return {"error": "未找到当前题目"}
    
    # Evaluate answer
    evaluation_result = _evaluate_answer_with_fallback(
        question=asked_q.question_text,
        correct_answer=asked_q.correct_answer_text,
        user_answer=answer_text
    )
    
    # Save evaluation - use upsert pattern with try-except for race conditions
    db.expire_all()  # Refresh session to see latest committed data
    
    existing_evaluation = db.query(Evaluation).filter(
        Evaluation.asked_question_id == asked_q.id
    ).first()
    
    if existing_evaluation:
        # Update existing evaluation
        existing_evaluation.answer_text = answer_text
        existing_evaluation.scores_json = evaluation_result["scores"]
        existing_evaluation.overall_score = evaluation_result["overall_score"]
        existing_evaluation.feedback_text = evaluation_result["feedback"]
        existing_evaluation.missing_points_json = evaluation_result["missing_points"]
        existing_evaluation.next_direction = evaluation_result["next_direction"]
        existing_evaluation.speech_analysis_json = audio_analysis
        existing_evaluation.expression_analysis_json = expression_analysis
        evaluation = existing_evaluation
    else:
        # Try to create new evaluation
        # If it fails due to duplicate key, update existing one
        try:
            evaluation = Evaluation(
                asked_question_id=asked_q.id,
                answer_text=answer_text,
                scores_json=evaluation_result["scores"],
                overall_score=evaluation_result["overall_score"],
                feedback_text=evaluation_result["feedback"],
                missing_points_json=evaluation_result["missing_points"],
                next_direction=evaluation_result["next_direction"],
                speech_analysis_json=audio_analysis,
                expression_analysis_json=expression_analysis
            )
            db.add(evaluation)
            db.flush()
        except IntegrityError as e:
            # If duplicate key error, rollback and update existing
            db.rollback()
            # Query again after rollback
            existing_evaluation = db.query(Evaluation).filter(
                Evaluation.asked_question_id == asked_q.id
            ).first()
            if existing_evaluation:
                existing_evaluation.answer_text = answer_text
                existing_evaluation.scores_json = evaluation_result["scores"]
                existing_evaluation.overall_score = evaluation_result["overall_score"]
                existing_evaluation.feedback_text = evaluation_result["feedback"]
                existing_evaluation.missing_points_json = evaluation_result["missing_points"]
                existing_evaluation.next_direction = evaluation_result["next_direction"]
                existing_evaluation.speech_analysis_json = audio_analysis
                existing_evaluation.expression_analysis_json = expression_analysis
                evaluation = existing_evaluation
            else:
                raise  # Re-raise if still can't find it
    
    db.flush()
    
    # Initialize adaptive engine
    adaptive_engine = AdaptiveInterviewEngine(db, session)
    
    # Calculate adaptive difficulty
    new_difficulty = adaptive_engine.calculate_adaptive_difficulty()
    
    # Check if should ask follow-up using adaptive algorithm
    should_followup, followup_reason = adaptive_engine.should_ask_followup(
        asked_question_id=asked_q.id,
        evaluation_score=evaluation_result["overall_score"],
        missing_points=evaluation_result.get("missing_points", [])
    )
    
    # Check if should end interview
    should_end, end_reason = adaptive_engine.should_end_interview()
    
    if should_end:
        # End interview
        return end_interview(db, session_id)
    
    if should_followup and session.current_round < session.total_rounds:
        # Generate follow-up question (LLM 优先，否则模板)
        followup_count = adaptive_engine._count_followups_for_question(asked_q.id)
        followup_content = _generate_followup(
            feedback=evaluation_result["feedback"],
            missing_points=evaluation_result.get("missing_points", []),
            original_question=asked_q.question_text,
            user_answer=answer_text or "",
            followup_count=followup_count,
            correct_answer=asked_q.correct_answer_text or "",
        )
        
        interviewer_turn = InterviewTurn(
            session_id=session_id,
            role="interviewer",
            content=followup_content
        )
        db.add(interviewer_turn)
        session.current_round += 1
        db.commit()
        
        return {
            "evaluation": evaluation_result,
            "followup": True,
            "interviewer_message": followup_content,
            "round": session.current_round,
            "followup_reason": followup_reason
        }
    else:
        # Move to next question
        # Double check if should end (adaptive check)
        should_end, end_reason = adaptive_engine.should_end_interview()
        if should_end:
            return end_interview(db, session_id)
        
        # Get resume skills and missing chapters
        resume_skills = None
        missing_chapters = []
        if session.resume_id:
            resume = db.query(Resume).filter(Resume.id == session.resume_id).first()
            if resume and resume.parsed_json:
                resume_skills = resume.parsed_json.get("skills", [])
        
        # Collect missing chapters from evaluations
        evaluations = db.query(Evaluation).join(AskedQuestion).filter(
            AskedQuestion.session_id == session_id
        ).order_by(Evaluation.created_at.desc()).all()
        for eval_obj in evaluations:
            if eval_obj.missing_points_json:
                aq = db.query(AskedQuestion).filter(AskedQuestion.id == eval_obj.asked_question_id).first()
                if aq and aq.topic:
                    missing_chapters.append(aq.topic)
        
        # 使用最近一次评估的 next_direction 作为选题提示（LLM 输出）
        next_direction_hints = []
        if evaluations and evaluations[0].next_direction:
            next_direction_hints = [evaluations[0].next_direction]
        
        # Select next question
        next_question = select_question(
            db=db,
            session=session,
            current_difficulty=new_difficulty,
            resume_skills=resume_skills,
            missing_chapters=list(set(missing_chapters)),
            next_direction_hints=next_direction_hints
        )
        
        if not next_question:
            # No more questions, end interview
            return end_interview(db, session_id)
        
        # Create asked question
        next_asked_q = AskedQuestion(
            session_id=session_id,
            qbank_id=next_question.id,
            topic=next_question.chapter,
            difficulty=new_difficulty,
            question_text=next_question.question,
            correct_answer_text=next_question.correct_answer
        )
        db.add(next_asked_q)
        
        # Create interviewer turn (自适应过渡语)
        last_score = evaluation_result.get("overall_score")
        was_followup = adaptive_engine._count_followups_for_question(asked_q.id) > 0
        next_content = get_next_question_phrase(
            question=next_question.question,
            last_score=last_score,
            after_followup=was_followup,
            next_chapter=next_question.chapter,
        )
        interviewer_turn = InterviewTurn(
            session_id=session_id,
            role="interviewer",
            content=next_content
        )
        db.add(interviewer_turn)
        
        session.current_round += 1
        db.commit()
        
        return {
            "evaluation": evaluation_result,
            "followup": False,
            "next_question": next_question.question,
            "interviewer_message": interviewer_turn.content,
            "round": session.current_round
        }


def end_interview(db: Session, session_id: int) -> Dict:
    """End interview and generate report."""
    session = db.query(InterviewSession).filter(InterviewSession.id == session_id).first()
    if not session:
        return {"error": "面试会话不存在"}
    
    session.status = "completed"
    session.ended_at = datetime.utcnow()
    
    # Create ending turn
    ending_turn = InterviewTurn(
        session_id=session_id,
        role="interviewer",
        content="感谢你的参与！面试已结束，正在生成报告..."
    )
    db.add(ending_turn)
    db.commit()
    
    return {
        "status": "completed",
        "message": "面试已结束，请查看报告页面。"
    }


def _evaluate_answer_with_fallback(
    question: str,
    correct_answer: str,
    user_answer: str
) -> Dict:
    """Evaluate answer: LLM primary (semantic understanding), rules as fallback."""
    # Short/garbage answers — fast reject without LLM cost
    if len((user_answer or "").strip()) < 10:
        return evaluate_answer(question, correct_answer, user_answer)

    # Try LLM first (understands semantics, gives fair partial credit)
    try:
        llm_result = evaluate_with_llm(question, correct_answer, user_answer)
        if llm_result:
            llm_result["_provenance"] = "llm"
            print(f"[eval] LLM scored: {llm_result.get('overall_score', 0):.2f}")
            return llm_result
        else:
            print("[eval] LLM returned None, falling back to rules")
    except Exception as e:
        print(f"[eval] LLM evaluation error: {e}, falling back to rules")

    # Fallback to rules
    rule_result = evaluate_answer(question, correct_answer, user_answer)
    rule_result["_provenance"] = "rule"
    print(f"[eval] Rule scored: {rule_result.get('overall_score', 0):.2f}")
    return rule_result


def _generate_followup(
    feedback: str,
    missing_points: List[str],
    original_question: str,
    user_answer: str = "",
    followup_count: int = 0,
    correct_answer: str = "",
) -> str:
    """Generate follow-up: memory-aware LLM > basic LLM > template."""
    # Try context-aware LLM follow-up first
    try:
        from backend.services.llm_provider import generate_followup_with_context
        ctx_result = generate_followup_with_context(
            original_question=original_question,
            user_answer=user_answer,
            correct_answer=correct_answer,
            feedback=feedback,
            missing_points=missing_points,
            followup_count=followup_count,
        )
        if ctx_result:
            return ctx_result
    except Exception:
        pass

    # Fallback to basic LLM
    llm_result = generate_followup_with_llm(
        original_question=original_question,
        user_answer=user_answer,
        feedback=feedback,
        missing_points=missing_points,
        followup_count=followup_count,
        correct_answer=correct_answer,
    )
    if llm_result:
        return llm_result
    return get_followup_phrase(missing_points, feedback)


def _normalize_candidate_display_content(content: str) -> str:
    """Replace voice placeholder / ASR-unconfigured text with a short friendly line for display."""
    if not content or not content.strip():
        return "（已提交语音回答）"
    s = content.strip()
    if s.startswith("[") or "需要配置语音" in s or "语音识别服务" in s or "[音频处理失败]" in s:
        return "（已提交语音回答）"
    if s.startswith("[语音回答]") and ("需要配置" in s or "语音识别" in s):
        return "（已提交语音回答）"
    return content


def get_session_turns(db: Session, session_id: int) -> List[Dict]:
    """Get all turns for a session. Candidate voice placeholders are normalized for display."""
    turns = db.query(InterviewTurn).filter(
        InterviewTurn.session_id == session_id
    ).order_by(InterviewTurn.created_at).all()
    
    return [
        {
            "id": turn.id,
            "role": turn.role,
            "content": _normalize_candidate_display_content(turn.content) if turn.role == "candidate" else turn.content,
            "created_at": turn.created_at
        }
        for turn in turns
    ]


# ======================================================================
# Agentic controller path (gated by enable_agent_controller feature flag)
# ======================================================================

def _submit_answer_agentic(
    db: Session,
    session_id: int,
    answer_text: Optional[str] = None,
    answer_type: str = "text",
    audio_data: Optional[Dict] = None,
    expression_data: Optional[Dict] = None,
) -> Dict:
    """Agentic version of submit_answer.

    Delegates core logic to AgentController while preserving the same
    DB writes (InterviewTurn, AskedQuestion, Evaluation) and return
    format so the Streamlit UI remains unaffected.
    """
    session = db.query(InterviewSession).filter(InterviewSession.id == session_id).first()
    if not session or session.status != "active":
        return {"error": "面试会话不存在或已结束"}

    # --- Pre-processing (identical to legacy) ---
    audio_analysis = None
    expression_analysis = None

    if expression_data:
        if expression_data.get("analyses"):
            analyses = expression_data["analyses"]
            if analyses:
                latest = {k: v for k, v in analyses[-1].items() if not k.startswith("_")}
                expression_analysis = latest
            existing_history = session.expression_history_json or []
            for a in analyses:
                clean = {k: v for k, v in a.items() if not k.startswith("_")}
                existing_history.append(clean)
            session.expression_history_json = existing_history[-100:]
        elif expression_data.get("imageData"):
            expression_analysis = analyze_expression(expression_data["imageData"], enforce_detection=False)

    if answer_type == "audio":
        if not audio_data:
            return {"error": "音频数据为空"}
        processed_result = process_audio_answer(audio_data)
        answer_text = processed_result["text"]
        audio_analysis = processed_result["audio_analysis"]
        display_content = _normalize_candidate_display_content(answer_text if answer_text else "")
        candidate_turn = InterviewTurn(session_id=session_id, role="candidate", content=display_content)
        db.add(candidate_turn)
        db.flush()
    else:
        if not answer_text or not answer_text.strip():
            return {"error": "回答内容为空"}
        candidate_turn = InterviewTurn(session_id=session_id, role="candidate", content=answer_text)
        db.add(candidate_turn)
        db.flush()

    # Current asked question
    asked_q = db.query(AskedQuestion).filter(
        AskedQuestion.session_id == session_id
    ).order_by(AskedQuestion.created_at.desc()).first()
    if not asked_q:
        return {"error": "未找到当前题目"}

    # --- Agent controller ---
    from backend.agent.controller import AgentController

    agent = AgentController(db, session)
    agent_result = agent.process_answer(
        answer_text=answer_text or "",
        asked_question=asked_q,
        audio_analysis=audio_analysis,
        expression_analysis=expression_analysis,
    )

    evaluation_result = agent_result.get("evaluation", {})

    # --- Save evaluation (same upsert pattern as legacy) ---
    from sqlalchemy.exc import IntegrityError as _IntegrityError

    db.expire_all()
    existing_eval = db.query(Evaluation).filter(Evaluation.asked_question_id == asked_q.id).first()

    eval_scores = dict(evaluation_result.get("scores", {}) or {})
    policy_meta = evaluation_result.get("policy_meta")
    if isinstance(policy_meta, dict) and policy_meta:
        eval_scores["_agentic_meta"] = policy_meta

    eval_fields = dict(
        answer_text=answer_text or "",
        scores_json=eval_scores,
        overall_score=evaluation_result.get("overall_score", 0.0),
        feedback_text=evaluation_result.get("feedback", ""),
        missing_points_json=evaluation_result.get("missing_points"),
        next_direction=evaluation_result.get("next_direction"),
        speech_analysis_json=audio_analysis,
        expression_analysis_json=expression_analysis,
    )

    if existing_eval:
        for k, v in eval_fields.items():
            setattr(existing_eval, k, v)
    else:
        try:
            evaluation = Evaluation(asked_question_id=asked_q.id, **eval_fields)
            db.add(evaluation)
            db.flush()
        except _IntegrityError:
            db.rollback()
            existing_eval = db.query(Evaluation).filter(Evaluation.asked_question_id == asked_q.id).first()
            if existing_eval:
                for k, v in eval_fields.items():
                    setattr(existing_eval, k, v)
            else:
                raise
    db.flush()

    # --- Dispatch agent action ---
    agent_action = agent_result.get("_agent_action", "terminate")

    if agent_action == "terminate":
        return end_interview(db, session_id)

    if agent_action == "follow_up":
        followup_content = agent_result.get("followup_text", "")
        interviewer_turn = InterviewTurn(
            session_id=session_id, role="interviewer", content=followup_content
        )
        db.add(interviewer_turn)
        session.current_round += 1
        db.commit()
        return {
            "evaluation": evaluation_result,
            "followup": True,
            "interviewer_message": followup_content,
            "round": session.current_round,
            "followup_reason": agent_result.get("_agent_reason", ""),
        }

    # ask_next
    next_q_obj = agent_result.get("next_question_obj")
    if not next_q_obj:
        return end_interview(db, session_id)

    new_diff = agent_result.get("new_difficulty", session.level)
    next_asked_q = AskedQuestion(
        session_id=session_id,
        qbank_id=next_q_obj.id,
        topic=next_q_obj.chapter,
        difficulty=new_diff,
        question_text=next_q_obj.question,
        correct_answer_text=next_q_obj.correct_answer,
    )
    db.add(next_asked_q)

    last_score = evaluation_result.get("overall_score")
    was_followup = agent.memory.followup_counts.get(str(asked_q.id), 0) > 0
    next_content = get_next_question_phrase(
        question=next_q_obj.question,
        last_score=last_score,
        after_followup=was_followup,
        next_chapter=next_q_obj.chapter,
    )
    interviewer_turn = InterviewTurn(
        session_id=session_id, role="interviewer", content=next_content
    )
    db.add(interviewer_turn)
    session.current_round += 1
    db.commit()

    return {
        "evaluation": evaluation_result,
        "followup": False,
        "next_question": next_q_obj.question,
        "interviewer_message": interviewer_turn.content,
        "round": session.current_round,
    }

